# Generated by Django 3.2.8 on 2021-10-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_postcreate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCreate',
            new_name='Post',
        ),
    ]
