# Generated by Django 3.2.8 on 2021-10-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_postcreate_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
