# Generated by Django 3.2.8 on 2021-10-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_post_user'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='post',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='users.user'),
        # ),
    ]
