# Generated by Django 3.2.8 on 2021-10-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_article_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_id', models.IntegerField(max_length=100)),
                ('state_code', models.CharField(max_length=100, null=True)),
                ('country_id', models.IntegerField(max_length=100, null=True)),
                ('country_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('wikiDataId', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Select Country')),
                ('phonecode', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.IntegerField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('state_code', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
            ],
        ),
    ]
